import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {computeThemes,filterReasons,parseRoute,themeForTicker,tickersLine,loosenFor}=new Function(`${readFileSync(new URL('../themes.js',import.meta.url),'utf8')};return THEME_TRACKER`)();
const c=(ticker,adr,dv,d,y,ext=2)=>({ticker,name:ticker,adr,dv,ext,ret:{d,y}});
const data={companies:{NVDA:c('NVDA',2.577,2e10,-2,17),META:c('META',3.1,1e9,-1,30),TSLA:c('TSLA',4,1e9,2,null),AAPL:c('AAPL',1.5,1e9,1,10)},themes:[{id:'mag-7',name:'Mag 7',tickers:['NVDA','META','TSLA','AAPL']}]};
assert.equal(computeThemes(data)[0].rows.length,4);
assert.equal(computeThemes(data,{query:'NVDA'}).length,1,'ticker search still surfaces the theme');
assert.equal(computeThemes(data,{query:'NVDA'})[0].rows[0].ticker,'NVDA');
assert.match(filterReasons(data.companies.NVDA,{minAdr:3})[0],/2.58% < 3%/);
assert.equal(computeThemes(data,{query:'NVDA',minAdr:2.5})[0].rows[0].ticker,'NVDA');
assert.equal(computeThemes(data,{minAdr:0})[0].rows.length,4);
assert.equal(computeThemes(data)[0].mean,0.5);
assert.equal(computeThemes(data,{query:'META'})[0].mean,0.5,'search must not redefine group return');
assert.equal(computeThemes(data,{window:'y'})[0].mean,30,'missing YTD is excluded, not zero');
assert.equal(filterReasons({...data.companies.META,ext:0},{aboveOnly:true}).length,1);
assert.equal(filterReasons({...data.companies.META,ext:null},{aboveOnly:true})[0],'50-day SMA unavailable');
assert.deepEqual(parseRoute('#themes/lookup/NVDA'),{query:'nvda',selected:null});
assert.deepEqual(parseRoute('#themes/lookup/BRK%2EB'),{query:'brk.b',selected:null});
assert.deepEqual(parseRoute('#themes/semiconductors'),{query:null,selected:'semiconductors'});
const both={companies:data.companies,themes:[{id:'semiconductors',name:'Semiconductors',tickers:['NVDA']},{id:'mag-7',name:'Mag 7',tickers:['NVDA','META','TSLA','AAPL']}]};
assert.equal(themeForTicker(both,'NVDA').id,'semiconductors');
assert.equal(themeForTicker(data,'AAPL').id,'mag-7');
assert.equal(tickersLine([{ticker:'NVDA'},{ticker:'META'}]),'NVDA, META');
const withA={companies:{...data.companies,'HEI.A':c('HEI.A',4,2e8,1,10)},themes:[{id:'aero',name:'Aerospace',tickers:['HEI.A','META']}]};
assert.equal(computeThemes(withA)[0].rows.some(r => r.ticker==='HEI.A'), false);
const mixed={companies:data.companies,themes:[{id:'semiconductors',name:'Semis',tickers:['META']},{id:'retail',name:'Retail',tickers:['TSLA']}]};
assert.deepEqual(computeThemes(mixed,{scope:'focus'}).map(t=>t.id),['semiconductors']);
assert.equal(computeThemes(mixed,{scope:'all'}).length,2);
assert.equal(computeThemes(mixed,{scope:'focus',query:'tsla'}).some(t=>t.id==='retail'),true);
const health={companies:data.companies,themes:[{id:'healthcare-biotech',name:'Healthcare',tickers:['META']}]};
assert.equal(computeThemes(health,{scope:'focus'})[0].id,'healthcare-biotech');
assert.deepEqual(loosenFor({adr:2.577,dv:2e10,ext:3},{minAdr:3,minDv:100,aboveOnly:false}),{minAdr:2.5,minDv:100,aboveOnly:false});
console.log('Themes: 23 assertions passed');
